package com.example.demo.model.generatedFreeFormatter;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.06 at 12:01:25 PM CEST 
//


import com.example.demo.model.generatedFreeFormatter.CrisResults;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CrisResults }
     * 
     */
    public CrisResults createCrisResults() {
        return new CrisResults();
    }

    /**
     * Create an instance of {@link CrisResults.PaperJournal }
     * 
     */
    public CrisResults.PaperJournal createCrisResultsPaperJournal() {
        return new CrisResults.PaperJournal();
    }

    /**
     * Create an instance of {@link CrisResults.PaperJournal.Authors }
     * 
     */
    public CrisResults.PaperJournal.Authors createCrisResultsPaperJournalAuthors() {
        return new CrisResults.PaperJournal.Authors();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference }
     * 
     */
    public CrisResults.PaperConference createCrisResultsPaperConference() {
        return new CrisResults.PaperConference();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference.BoardMembers }
     * 
     */
    public CrisResults.PaperConference.BoardMembers createCrisResultsPaperConferenceBoardMembers() {
        return new CrisResults.PaperConference.BoardMembers();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference.Advisors }
     * 
     */
    public CrisResults.PaperConference.Advisors createCrisResultsPaperConferenceAdvisors() {
        return new CrisResults.PaperConference.Advisors();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference.Author }
     * 
     */
    public CrisResults.PaperConference.Author createCrisResultsPaperConferenceAuthor() {
        return new CrisResults.PaperConference.Author();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference.Authors }
     * 
     */
    public CrisResults.PaperConference.Authors createCrisResultsPaperConferenceAuthors() {
        return new CrisResults.PaperConference.Authors();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference.Proceedings }
     * 
     */
    public CrisResults.PaperConference.Proceedings createCrisResultsPaperConferenceProceedings() {
        return new CrisResults.PaperConference.Proceedings();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference.Proceedings.Editors }
     * 
     */
    public CrisResults.PaperConference.Proceedings.Editors createCrisResultsPaperConferenceProceedingsEditors() {
        return new CrisResults.PaperConference.Proceedings.Editors();
    }

    /**
     * Create an instance of {@link CrisResults.Monograph }
     * 
     */
    public CrisResults.Monograph createCrisResultsMonograph() {
        return new CrisResults.Monograph();
    }

    /**
     * Create an instance of {@link CrisResults.Monograph.Authors }
     * 
     */
    public CrisResults.Monograph.Authors createCrisResultsMonographAuthors() {
        return new CrisResults.Monograph.Authors();
    }

    /**
     * Create an instance of {@link CrisResults.Theses }
     * 
     */
    public CrisResults.Theses createCrisResultsTheses() {
        return new CrisResults.Theses();
    }

    /**
     * Create an instance of {@link CrisResults.Theses.BoardMembers }
     * 
     */
    public CrisResults.Theses.BoardMembers createCrisResultsThesesBoardMembers() {
        return new CrisResults.Theses.BoardMembers();
    }

    /**
     * Create an instance of {@link CrisResults.Theses.Advisors }
     * 
     */
    public CrisResults.Theses.Advisors createCrisResultsThesesAdvisors() {
        return new CrisResults.Theses.Advisors();
    }

    /**
     * Create an instance of {@link CrisResults.Theses.Author }
     * 
     */
    public CrisResults.Theses.Author createCrisResultsThesesAuthor() {
        return new CrisResults.Theses.Author();
    }

    /**
     * Create an instance of {@link CrisResults.PaperJournal.Evaluation }
     * 
     */
    public CrisResults.PaperJournal.Evaluation createCrisResultsPaperJournalEvaluation() {
        return new CrisResults.PaperJournal.Evaluation();
    }

    /**
     * Create an instance of {@link CrisResults.PaperJournal.Journal }
     * 
     */
    public CrisResults.PaperJournal.Journal createCrisResultsPaperJournalJournal() {
        return new CrisResults.PaperJournal.Journal();
    }

    /**
     * Create an instance of {@link CrisResults.PaperJournal.Authors.Researcher }
     * 
     */
    public CrisResults.PaperJournal.Authors.Researcher createCrisResultsPaperJournalAuthorsResearcher() {
        return new CrisResults.PaperJournal.Authors.Researcher();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference.Evaluation }
     * 
     */
    public CrisResults.PaperConference.Evaluation createCrisResultsPaperConferenceEvaluation() {
        return new CrisResults.PaperConference.Evaluation();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference.Conference }
     * 
     */
    public CrisResults.PaperConference.Conference createCrisResultsPaperConferenceConference() {
        return new CrisResults.PaperConference.Conference();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference.BoardMembers.Researcher }
     * 
     */
    public CrisResults.PaperConference.BoardMembers.Researcher createCrisResultsPaperConferenceBoardMembersResearcher() {
        return new CrisResults.PaperConference.BoardMembers.Researcher();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference.Advisors.Researcher }
     * 
     */
    public CrisResults.PaperConference.Advisors.Researcher createCrisResultsPaperConferenceAdvisorsResearcher() {
        return new CrisResults.PaperConference.Advisors.Researcher();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference.Author.Researcher }
     * 
     */
    public CrisResults.PaperConference.Author.Researcher createCrisResultsPaperConferenceAuthorResearcher() {
        return new CrisResults.PaperConference.Author.Researcher();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference.Authors.Researcher }
     * 
     */
    public CrisResults.PaperConference.Authors.Researcher createCrisResultsPaperConferenceAuthorsResearcher() {
        return new CrisResults.PaperConference.Authors.Researcher();
    }

    /**
     * Create an instance of {@link CrisResults.PaperConference.Proceedings.Editors.Researcher }
     * 
     */
    public CrisResults.PaperConference.Proceedings.Editors.Researcher createCrisResultsPaperConferenceProceedingsEditorsResearcher() {
        return new CrisResults.PaperConference.Proceedings.Editors.Researcher();
    }

    /**
     * Create an instance of {@link CrisResults.Monograph.Evaluation }
     * 
     */
    public CrisResults.Monograph.Evaluation createCrisResultsMonographEvaluation() {
        return new CrisResults.Monograph.Evaluation();
    }

    /**
     * Create an instance of {@link CrisResults.Monograph.Authors.Researcher }
     * 
     */
    public CrisResults.Monograph.Authors.Researcher createCrisResultsMonographAuthorsResearcher() {
        return new CrisResults.Monograph.Authors.Researcher();
    }

    /**
     * Create an instance of {@link CrisResults.Theses.Evaluation }
     * 
     */
    public CrisResults.Theses.Evaluation createCrisResultsThesesEvaluation() {
        return new CrisResults.Theses.Evaluation();
    }

    /**
     * Create an instance of {@link CrisResults.Theses.BoardMembers.Researcher }
     * 
     */
    public CrisResults.Theses.BoardMembers.Researcher createCrisResultsThesesBoardMembersResearcher() {
        return new CrisResults.Theses.BoardMembers.Researcher();
    }

    /**
     * Create an instance of {@link CrisResults.Theses.Advisors.Researcher }
     * 
     */
    public CrisResults.Theses.Advisors.Researcher createCrisResultsThesesAdvisorsResearcher() {
        return new CrisResults.Theses.Advisors.Researcher();
    }

    /**
     * Create an instance of {@link CrisResults.Theses.Author.Researcher }
     * 
     */
    public CrisResults.Theses.Author.Researcher createCrisResultsThesesAuthorResearcher() {
        return new CrisResults.Theses.Author.Researcher();
    }

}
